version: 0.0
Resources:
  - TargetService:
      Type: AWS::ECS::Service
      Properties:
        TaskDefinition: <TASK_DEFINITION>
        LoadBalancerInfo:
          ContainerName: "nginx"
          ContainerPort: 80
        PlatformVersion: "LATEST"
Hooks:
  BeforeInstall: "BeforeInstall"
  AfterInstall: "AfterInstall"
  AfterAllowTestTraffic: "AfterAllowTestTraffic"
  BeforeAllowTraffic: "BeforeAllowTraffic"
  AfterAllowTraffic: "AfterAllowTraffic"