version: 0.2
phases:
 install:
   commands:

 build:
   commands:
     - echo Build started on `date`
     - echo Installing composer deps

 post_build:
   commands:
     - echo Build completed on `date`
artifacts:
  files:
    - '**/*'
  base-directory: base_dir
  name: build-artifact-name
  discard-paths: no
