version: 0.2
phases:
 install:
   commands:

 build:
   commands:
     - echo Build started on `date`
     - echo Installing composer deps
     - composer install --no-progress

 post_build:
   commands:
     - echo Build completed on `date`
