version: 0.2

env:
  variables:
    AWS_REGION: us-west-1
    AWS_ACCOUNT_ID: 450370295967
    IMAGE_NAME: laravel-app

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $ECR_REPO
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - IMAGE_TAG=${COMMIT_HASH:=latest}
  build:
    commands:
      - echo Build started on `date`
      - docker build -t $ECR_REPO:$IMAGE_TAG ./docker
      - docker tag $ECR_REPO:$IMAGE_TAG $ECR_REPO:latest

  post_build:
    commands:
      - echo Build completed on `date`
      - docker push $ECR_REPO:$IMAGE_TAG
      - docker push $ECR_REPO:latest
      - printf '{"ImageURI":"%s"}' $ECR_REPO:$IMAGE_TAG > imageDetail.json
      - printf '{"Version":{"Ref":"Version"},"ServiceName":{"Ref":"ServiceName"},"ImageURI":"%s"}' $ECR_REPO:$IMAGE_TAG > taskdef.json
      - cat taskdef.json
      - cat appspec.yaml
artifacts:
  files:
    - appspec.yml
    - taskdef.json
    - imageDetail.json
