version: 0.2

env:
  variables:
    AWS_REGION: us-west-1
    AWS_ACCOUNT_ID: 450370295967
    IMAGE_NAME: laravel-app

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $ECR_REPO
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - IMAGE_TAG=${COMMIT_HASH:=latest}
  build:
    commands:
      - echo Build started on `date`
      - echo $ECR_REPO
      - docker build -f docker/php/Dockerfile -t $ECR_REPO:$IMAGE_TAG .
      - docker tag $ECR_REPO:$IMAGE_TAG $ECR_REPO:latest

  post_build:
    commands:
      - echo Build completed on `date`
      - docker push $ECR_REPO:$IMAGE_TAG
      - docker push $ECR_REPO:latest
      - printf '{"ImageURI":"%s"}' $ECR_REPO:$IMAGE_TAG > imageDetail.json
      - sed -i "s|<PHP_IMAGE>|$ECR_REPO:$IMAGE_TAG|g" taskdef.json
      - echo "Files in current directory:"
      - ls -la
      - echo "Contents of appspec.yml:"
      - cat appspec.yml
      - echo "Contents of taskdef.json:"
      - cat taskdef.json

artifacts:
  files:
    - 'image*.json'
    - 'appspec.yml'
    - 'taskdef.json'
  secondary-artifacts:
    DefinitionArtifact:
      files:
        - appspec.yaml
        - taskdef.json
    ImageArtifact:
      files:
        - imageDetail.json
